language: node_js

node_js:
  - lts/dubnium

jobs:
  include:
    - stage: test
      name: 'Linting and testing'
      scripts:
        - yarn lint
        - yarn test
    - stage: build
      name: 'Building and deploying to NPM'
      before_deploy:
        - yarn build
      deploy:
        - provider: script
          edge: true
          script: npx semantic-release
          on:
            branch: master
